name: Build Qt CMake Project

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  UPLOAD_DIR: upload
  BUILD_TYPE: Release
  BUILD_TEST: ON
  UPDATE_TRANSLATIONS: OFF

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
            - os: ubuntu-latest
            # - os: windows-latest
            # - os: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Extract Python Version from Pipfile
      id: extract_python
      shell: bash
      run: |
        PYTHON_VERSION=$(awk -F'"' '/python_version/ { print $2 }' Pipfile)
        echo "Found Python version: ${PYTHON_VERSION}"
        echo "python-version=${PYTHON_VERSION}" >> "$GITHUB_OUTPUT"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ steps.extract_python.outputs.python-version }}

    - name: Install Pipenv
      shell: bash
      run: |
        pip install --user pipenv
        PYTHON_BIN="$(python -m site --user-base)/bin"
        echo "${PYTHON_BIN}" >> "${GITHUB_PATH}"
        export PATH="${PYTHON_BIN}:${PATH}"
        pipenv install

    - name: Install System Dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          libgl1-mesa-dev \
          libxkbcommon-x11-0 \
          libxcb-cursor-dev \
          fuse \
          libfuse2 \
          imagemagick \
          patchelf \
          clang-tidy

    - name: Confirm OpenGL (macOS)
      if: runner.os == 'macOS'
      run: system_profiler SPSoftwareDataType

    - name: Configure MSVC Environment (Windows)
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Deployment Tools (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        choco install innosetup

    - name: Install Qt (All)
      shell: bash
      run: |
        ./scripts/install-qt.sh

    - name: Set Qt PATH for Test Discovery
      shell: bash
      if: env.BUILD_TEST == 'ON'
      run: |
        source ./scripts/env.sh
        echo "PATH=${QT_BIN}:${PATH}" >> ${GITHUB_ENV}
        echo "QT_QPA_PLATFORM=offscreen" >> ${GITHUB_ENV}

    - name: Configure and Build (All)
      shell: bash
      run: |
        ./scripts/build.sh \
          --build-type ${{ env.BUILD_TYPE }} \
          --test ${{ env.BUILD_TEST }} \
          --update-translations ${{ env.UPDATE_TRANSLATIONS }}

    - name: Unit Tests (All)
      shell: bash
      if: env.BUILD_TEST == 'ON'
      run: |
        source ./scripts/env.sh
        
        if [ "${PLATFORM}" == "windows" ]; then
          export WINDEPLOYQT=$(cygpath -w "${QT_BIN}/windeployqt.exe")
          export EXE_PATH=$(cygpath -w "${BUILD_DIR}/${{ env.BUILD_TYPE }}/${UT_NAME}.exe")
          ${WINDEPLOYQT} "${EXE_PATH}"
        "${EXE_PATH}" --gtest_output=stderr
        else
          "${BUILD_DIR}/tests/${UT_NAME}" --gtest_output=stderr
        fi


    - name: Smoke Test (All)
      shell: bash
      run: |
        ./scripts/run.sh --build-type ${{ env.BUILD_TYPE }} --smoke-test

    - name: Static Analysis (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        source ./scripts/env.sh
        clang-tidy -p "${BUILD_DIR}" $(find "${PROJECT_ROOT}/src" -type f -regextype posix-extended -regex ".*\.(cpp|h)")

    - name: Bundle Application Native (Linux)
      if: runner.os == 'Linux'
      run: |
        source ./scripts/env.sh
        
        ARCHIVE_NAME="${APP_NAME}-${APP_VERSION}"
        SOURCE_BINARY_PATH="${BUILD_DIR}/${APP_NAME}"
        SOURCE_LICENSE_PATH="${PROJECT_ROOT}/LICENSE"
        SOURCE_README_PATH="${PROJECT_ROOT}/README.md"
        DESKTOP_TEMPLATE_NAME="${APP_ID}.desktop.in"
        DESKTOP_ENTRY_NAME="${APP_ID}.desktop"
        MAKEFILE_PREFIX="/usr/local"
        MAKEFILE_USER_PREFIX="\$(HOME)/.local"

        TARGET_ROOT_DIR="${PROJECT_ROOT}/${ARCHIVE_NAME}"

        mkdir -p "${TARGET_ROOT_DIR}"
        mkdir -p "${TARGET_ROOT_DIR}/bin"
        mkdir -p "${TARGET_ROOT_DIR}/share/applications"
        mkdir -p "${TARGET_ROOT_DIR}/share/icons/hicolor/scalable/apps"
        mkdir -p "${TARGET_ROOT_DIR}/share/icons/hicolor/16x16/apps"
        mkdir -p "${TARGET_ROOT_DIR}/share/icons/hicolor/24x24/apps"
        mkdir -p "${TARGET_ROOT_DIR}/share/icons/hicolor/32x32/apps"
        mkdir -p "${TARGET_ROOT_DIR}/share/icons/hicolor/48x48/apps"
        mkdir -p "${TARGET_ROOT_DIR}/share/icons/hicolor/64x64/apps"
        mkdir -p "${TARGET_ROOT_DIR}/share/icons/hicolor/128x128/apps"
        mkdir -p "${TARGET_ROOT_DIR}/share/icons/hicolor/256x256/apps"
        mkdir -p "${TARGET_ROOT_DIR}/share/icons/hicolor/512x512/apps"

        cp "${SOURCE_BINARY_PATH}" "${TARGET_ROOT_DIR}/bin/${APP_NAME}"
        chmod +x "${TARGET_ROOT_DIR}/bin/${APP_NAME}"
        patchelf --set-rpath '/usr/lib' "${TARGET_ROOT_DIR}/bin/${APP_NAME}"

        cat << EOF > "${TARGET_ROOT_DIR}/share/applications/${DESKTOP_TEMPLATE_NAME}"
        [Desktop Entry]
        Type=Application
        X-AppVersion=${APP_VERSION}
        Name=${APP_NAME}
        Exec=${APP_NAME}
        Icon=${APP_ID}
        Categories=${APP_CATEGORIES}
        StartupWMClass=${APP_NAME}
        EOF

        PNG_SIZES=(16x16 24x24 32x32 48x48 64x64 128x128 256x256 512x512)

        SOURCE_SVG_ICON="${ICONS_DIR}/app_icon.svg"
        SOURCE_PNG_1024_ICON="${ICONS_DIR}/app_icon.png"

        if [ -f "${SOURCE_SVG_ICON}" ]; then
            cp "${SOURCE_SVG_ICON}" "${TARGET_ROOT_DIR}/share/icons/hicolor/scalable/apps/${APP_ID}.svg"
            echo "  Copied SVG: $(basename "${SOURCE_SVG_ICON}")"
        else
            echo "Error: SVG icon not found at ${SOURCE_SVG_ICON}. Aborting."
            exit 1
        fi

        for size in "${PNG_SIZES[@]}"; do
            ICON_DIR="${TARGET_ROOT_DIR}/share/icons/hicolor/${size}/apps"
            mkdir -p "${ICON_DIR}"
            magick "${SOURCE_PNG_1024_ICON}" -resize "${size}" "${ICON_DIR}/${APP_ID}.png"
            echo "  Resized and copied PNG: ${APP_ID}.png to ${size}"
        done

        cp "${SOURCE_LICENSE_PATH}" "${TARGET_ROOT_DIR}/LICENSE"

        cp "${SOURCE_README_PATH}" "${TARGET_ROOT_DIR}/README.md"

        cat << EOF > "${TARGET_ROOT_DIR}/Makefile"

        PREFIX ?= ${MAKEFILE_PREFIX}

        USER_PREFIX := \$(HOME)/.local

        BIN_DIR := \$(PREFIX)/bin
        SHARE_APP_DIR := \$(PREFIX)/share/applications
        SHARE_ICON_DIR := \$(PREFIX)/share/icons/hicolor

        USER_BIN_DIR := \$(USER_PREFIX)/bin
        USER_SHARE_APP_DIR := \$(USER_PREFIX)/share/applications
        USER_SHARE_ICON_DIR := \$(USER_PREFIX)/share/icons/hicolor

        APP_EXECUTABLE := bin/${APP_NAME}

        DESKTOP_TEMPLATE := share/applications/${DESKTOP_TEMPLATE_NAME}
        DESKTOP_FILE_FINAL := ${DESKTOP_ENTRY_NAME}

        APP_ICON_NAME := ${APP_ID}
        PNG_SIZES := 16x16 24x24 32x32 48x48 64x64 128x128 256x256 512x512

        .PHONY: all install uninstall install-user uninstall-user clean

        all:

        install:
          @echo "Installing \$(APP_EXECUTABLE) to \$(BIN_DIR)..."
          mkdir -p "\$(BIN_DIR)"
          cp "\$(APP_EXECUTABLE)" "\$(BIN_DIR)/"
          chmod +x "\$(BIN_DIR)/${APP_NAME}"

          @echo "Creating and installing desktop file to \$(SHARE_APP_DIR)..."
          mkdir -p "\$(SHARE_APP_DIR)"
          
          sed "s|@APP_EXEC_PATH@|\$(BIN_DIR)/${APP_NAME}|g" "\$(DESKTOP_TEMPLATE)" > "\$(SHARE_APP_DIR)/\$(DESKTOP_FILE_FINAL)"

          @echo "Installing icons to \$(SHARE_ICON_DIR)..."
          
          mkdir -p "\$(SHARE_ICON_DIR)/scalable/apps"
          cp "share/icons/hicolor/scalable/apps/\$(APP_ICON_NAME).svg" "\$(SHARE_ICON_DIR)/scalable/apps/"
          
          \$(foreach size,\$(PNG_SIZES),\
            mkdir -p "\$(SHARE_ICON_DIR)/\$(size)/apps" && \
            cp "share/icons/hicolor/\$(size)/apps/\$(APP_ICON_NAME).png" "\$(SHARE_ICON_DIR)/\$(size)/apps/" ;\
          )
          @echo "Updating desktop database..."
          update-desktop-database "\$(SHARE_APP_DIR)" || true

          @echo "Updating icon cache..."
          gtk-update-icon-cache -qtf "\$(SHARE_ICON_DIR)" || true
          @echo "Installation complete. You may need to log out and back in for icons/desktop entries to appear."

        uninstall:
          @echo "Uninstalling \$(APP_EXECUTABLE) from \$(BIN_DIR)..."
          rm -f "\$(BIN_DIR)/${APP_NAME}"

          @echo "Uninstalling desktop file from \$(SHARE_APP_DIR)..."
          rm -f "\$(SHARE_APP_DIR)/\$(DESKTOP_FILE_FINAL)"

          @echo "Uninstalling icons from \$(SHARE_ICON_DIR)..."
          rm -f "\$(SHARE_ICON_DIR)/scalable/apps/\$(APP_ICON_NAME).svg"
          \$(foreach size,\$(PNG_SIZES),\
            rm -f "\$(SHARE_ICON_DIR)/\$(size)/apps/\$(APP_ICON_NAME).png" ;\
          )
          @echo "Updating desktop database..."
          update-desktop-database "\$(SHARE_APP_DIR)" || true
          @echo "Updating icon cache..."
          gtk-update-icon-cache -qtf "\$(SHARE_ICON_DIR)" || true
          @echo "Uninstallation complete."

        install-user:
          @echo "Installing \$(APP_EXECUTABLE) to \$(USER_BIN_DIR)..."
          mkdir -p "\$(USER_BIN_DIR)"
          cp "\$(APP_EXECUTABLE)" "\$(USER_BIN_DIR)/"
          chmod +x "\$(USER_BIN_DIR)/${APP_NAME}"

          @echo "Creating and installing desktop file to \$(USER_SHARE_APP_DIR)..."
          mkdir -p "\$(USER_SHARE_APP_DIR)"
          
          sed "s|@APP_EXEC_PATH@|\$(USER_BIN_DIR)/${APP_NAME}|g" "\$(DESKTOP_TEMPLATE)" > "\$(USER_SHARE_APP_DIR)/\$(DESKTOP_FILE_FINAL)"

          @echo "Installing icons to \$(USER_SHARE_ICON_DIR)..."
          
          mkdir -p "\$(USER_SHARE_ICON_DIR)/scalable/apps"
          cp "share/icons/hicolor/scalable/apps/\$(APP_ICON_NAME).svg" "\$(USER_SHARE_ICON_DIR)/scalable/apps/"
          
          \$(foreach size,\$(PNG_SIZES),\
            mkdir -p "\$(USER_SHARE_ICON_DIR)/\$(size)/apps" && \
            cp "share/icons/hicolor/\$(size)/apps/\$(APP_ICON_NAME).png" "\$(USER_SHARE_ICON_DIR)/\$(size)/apps/" ;\
          )
          @echo "Updating desktop database..."
          update-desktop-database "\$(USER_SHARE_APP_DIR)" || true
          @echo "Updating icon cache..."
          gtk-update-icon-cache -qtf "\$(USER_SHARE_ICON_DIR)" || true
          @echo "User installation complete. You may need to log out and back in for icons/desktop entries to appear."

        uninstall-user:
          @echo "Uninstalling \$(APP_EXECUTABLE) from \$(USER_BIN_DIR)..."
          rm -f "\$(USER_BIN_DIR)/${APP_NAME}"

          @echo "Uninstalling desktop file from \$(USER_SHARE_APP_DIR)..."
          rm -f "\$(USER_SHARE_APP_DIR)/\$(DESKTOP_FILE_FINAL)"

          @echo "Uninstalling icons from \$(USER_SHARE_ICON_DIR)..."
          rm -f "\$(USER_SHARE_ICON_DIR)/scalable/apps/\$(APP_ICON_NAME).svg"
          \$(foreach size,\$(PNG_SIZES),\
            rm -f "\$(USER_SHARE_ICON_DIR)/\$(size)/apps/\$(APP_ICON_NAME).png" ;\
          )
          @echo "Updating desktop database..."
          update-desktop-database "\$(USER_SHARE_APP_DIR)" || true
          @echo "Updating icon cache..."
          gtk-update-icon-cache -qtf "\$(USER_SHARE_ICON_DIR)" || true
          @echo "User uninstallation complete."

        clean:
          
        EOF

        tar -czvf "${PROJECT_ROOT}/${ARCHIVE_NAME}.tar.gz" -C "$(dirname "${TARGET_ROOT_DIR}")" "$(basename "${TARGET_ROOT_DIR}")"

        rm -rf "${TARGET_ROOT_DIR}"


    - name: Bundle Application AppImage (Linux)
      if: runner.os == 'Linux'
      run: |
        source ./scripts/env.sh

        export APP_DIR="${APP_NAME}.AppDir"
        export BIN_DIR="${APP_DIR}/usr/bin"
        export LIB_DIR="${APP_DIR}/usr/lib"
        export APP_BIN="${BIN_DIR}/${APP_NAME}"

        export APP_PLUGINS_DIR="${APP_DIR}/usr/plugins"

        echo "Installing appimagetool..."
        wget https://github.com/AppImage/AppImageKit/releases/latest/download/appimagetool-x86_64.AppImage -O appimagetool
        chmod +x appimagetool

        echo "Setting up AppDir..."
        mkdir -p "${BIN_DIR}"
        mkdir -p "${LIB_DIR}"
        mkdir -p "${APP_PLUGINS_DIR}"
        cp -r "${QT_PLUGINS_DIR}/." "${APP_PLUGINS_DIR}/"
        cp "${BUILD_DIR}/${APP_NAME}" "${APP_BIN}"
        chmod +x "${APP_BIN}"

        seen_deps=()
        deps=()

        gather_deps() {
          local bin="$1"
          while IFS= read -r dep; do
            [[ -z "${dep}" ]] && continue

            if [[ ! -e "${dep}" ]]; then
              echo "ERROR: Dependency not found or broken symlink: ${dep}" >&2
              exit 1
            fi

            for existing in "${seen_deps[@]}"; do
              [[ "${existing}" == "${dep}" ]] && continue 2
            done

            seen_deps+=("${dep}")
            deps+=("${dep}")
            gather_deps "${dep}"
          done < <(ldd "${bin}" | awk '/=>/ {print $3}' | grep -v '^(')
        }

        echo "Gathering dependencies..."
        gather_deps "${APP_BIN}"

        echo "Getting dependency blacklist..."
        EXCLUDELIST_PATH="${{ runner.temp }}/appimage_excludelist"
        wget -qO "${EXCLUDELIST_PATH}" https://raw.githubusercontent.com/AppImage/pkg2appimage/master/excludelist
        BLACKLIST_REGEX=$(grep -vE '^\s*#|^\s*$' "${EXCLUDELIST_PATH}" | \
          cut -d'#' -f1 | \
          sed -E 's/^[[:space:]]+|[[:space:]]+$//g' | \
          sed -E 's/[][\.^$]/\\&/g' | \
          sed 's/^/^/' | \
          sed 's/$/$/' | \
          paste -sd'|' -)

        echo "Copying dependencies..."
        for dep in "${deps[@]}"; do
          real_dep=$(readlink -f "${dep}")
          base=$(basename "${real_dep}")
          if [[ ! "${base}" =~ ${BLACKLIST_REGEX} ]]; then
            cp -v "${dep}" "${LIB_DIR}/" || true
          else
            echo "Skipping blacklisted dependency: ${base}"
          fi
        done

        echo "Patching RPATH..."
        patchelf --set-rpath '$ORIGIN/../lib' "${APP_BIN}"

        echo "Finalizing AppDir..."
        cat > "${APP_DIR}/AppRun" <<EOF
        #!/bin/sh
        export QT_PLUGIN_PATH="\${APPDIR}/usr/plugins"
        "\${APPDIR}/usr/bin/${APP_NAME}" "\$@"
        EOF
        chmod +x "${APP_DIR}/AppRun"

        cat > "${APP_DIR}/${APP_ID}.desktop" <<EOF
        [Desktop Entry]
        Type=Application
        X-AppVersion=${APP_VERSION}
        Name=${APP_NAME}
        Exec=${APP_NAME}
        Icon=${APP_ID}
        Categories=${APP_CATEGORIES}
        StartupWMClass=${APP_NAME}
        EOF

        magick "${APP_ICON}" "${APP_DIR}/${APP_ID}.png"


        echo "Building AppImage..."
        rm -rf "${APP_NAME}-x86_64.AppImage"
        rm -rf "${APP_NAME}.AppImage"
        ./appimagetool "${APP_DIR}"
        mv "${APP_NAME}-x86_64.AppImage" "${BUILD_DIR}/${APP_NAME}.AppImage"

    - name: Bundle Application (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        source ./scripts/env.sh
        export APP_PATH="${BUILD_DIR}/${APP_NAME}.app"
        "${QT_BIN}/macdeployqt" "${APP_PATH}"

    - name: Bundle Application (Windows)
      if: runner.os == 'Windows'
      shell: bash
      run: |
        source ./scripts/env.sh
        export WINDEPLOYQT=$(cygpath -w "${QT_BIN}/windeployqt.exe")
        export EXE_PATH=$(cygpath -w "${BUILD_DIR}/${{ env.BUILD_TYPE }}/${APP_NAME}.exe")

        ${WINDEPLOYQT} "${EXE_PATH}"
        
        export ISS_PATH=$(cygpath -w "${{ github.workspace }}/inno.iss")
        cat > "${ISS_PATH}" <<EOF
        [Setup]
        AppName=${APP_NAME}
        AppVersion=${APP_VERSION}
        DefaultDirName={commonpf}\\${APP_NAME}
        OutputDir=${BUILD_DIR}
        OutputBaseFilename=${APP_NAME}Installer
        Compression=lzma
        SolidCompression=yes
        SetupIconFile=${APP_ICON}

        [Files]
        Source: "${BUILD_DIR}\\${{ env.BUILD_TYPE }}\\${APP_NAME}.exe"; DestDir: "{app}"; Flags: ignoreversion
        Source: "${BUILD_DIR}\\${{ env.BUILD_TYPE }}\\*.dll"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs
        Source: "${BUILD_DIR}\\${{ env.BUILD_TYPE }}\\platforms\\*"; DestDir: "{app}\\platforms"; Flags: ignoreversion recursesubdirs

        [Icons]
        Name: "{group}\\${APP_NAME}"; Filename: "{app}\\${APP_NAME}.exe"
        Name: "{commondesktop}\\${APP_NAME}"; Filename: "{app}\\${APP_NAME}.exe"
        EOF

        cat "${ISS_PATH}"
        iscc "${ISS_PATH}"

    - name: Move Artifact to Uploads
      shell: bash
      run: |
        source ./scripts/env.sh
        mkdir -p "${{ env.UPLOAD_DIR }}"
        
        if [ -e "${BUILD_DIR}/${APP_NAME}.AppImage" ]; then
          mv -v "${BUILD_DIR}/${APP_NAME}.AppImage" "${{ env.UPLOAD_DIR }}"
        fi
        
        if [ -e "${BUILD_DIR}/${APP_NAME}-${APP_VERSION}.tar.gz" ]; then
          mv -v "${BUILD_DIR}/${APP_NAME}-${APP_VERSION}.tar.gz" "${{ env.UPLOAD_DIR }}"
        fi

        if [ -e "${BUILD_DIR}/${APP_NAME}.app" ]; then
          mv -v "${BUILD_DIR}/${APP_NAME}.app" "${{ env.UPLOAD_DIR }}"
        fi

        if [ -e "${BUILD_DIR}/${APP_NAME}Installer.exe" ]; then
          mv -v "${BUILD_DIR}/${APP_NAME}Installer.exe" "${{ env.UPLOAD_DIR }}"
        fi

    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}
        path: ${{ env.UPLOAD_DIR }}