name: Build Qt CMake Project

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  QT_VERSION: 6.9.1

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
            - os: ubuntu-latest
              compiler_name: gcc_64
              compiler_dir: gcc_64
              aqt_platform: linux
            - os: windows-latest
              compiler_name: win64_msvc2019_64
              compiler_dir: msvc2019_64
              aqt_platform: windows
            - os: macos-latest
              compiler_name: clang_64
              compiler_dir: clang_64
              aqt_platform: mac

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5

    - name: Install Qt
      shell: bash
      run: |
        pip install aqtinstall
        aqt install-qt ${{ matrix.aqt_platform }} desktop ${{ env.QT_VERSION }} ${{ matrix.compiler_name }} -O ${{ runner.temp }}/Qt

    - name: Configure and Build
      shell: bash
      run: |
        export Qt6_DIR="${{ runner.temp }}/Qt/${{ env.QT_VERSION }}/${{ matrix.compiler_dir }}/lib/cmake/Qt6"
        cmake -B build -DCMAKE_PREFIX_PATH=$Qt6_DIR
        cmake --build build --parallel --config Release

    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: MyApp-${{ matrix.os }}
        path: |
          build/MyApp
          build/MyApp.exe
