name: Build Qt CMake Project

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  UPLOAD_DIR: upload
  BUILD_TYPE: Release
  BUILD_TEST: ON
  UPDATE_TRANSLATIONS: OFF

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
            - os: ubuntu-latest
            # - os: windows-latest
            # - os: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Extract Python Version from Pipfile
      id: extract_python
      shell: bash
      run: |
        PYTHON_VERSION=$(awk -F'"' '/python_version/ { print $2 }' Pipfile)
        echo "Found Python version: ${PYTHON_VERSION}"
        echo "python-version=${PYTHON_VERSION}" >> "$GITHUB_OUTPUT"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ steps.extract_python.outputs.python-version }}

    - name: Install Pipenv
      shell: bash
      run: |
        pip install --user pipenv
        PYTHON_BIN="$(python -m site --user-base)/bin"
        echo "${PYTHON_BIN}" >> "${GITHUB_PATH}"
        export PATH="${PYTHON_BIN}:${PATH}"
        pipenv install

    - name: Install System Dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          libgl1-mesa-dev \
          libxkbcommon-x11-0 \
          libxcb-cursor-dev \
          fuse \
          libfuse2 \
          imagemagick \
          patchelf \
          clang-tidy

    - name: Confirm OpenGL (macOS)
      if: runner.os == 'macOS'
      run: system_profiler SPSoftwareDataType

    - name: Configure MSVC Environment (Windows)
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Deployment Tools (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        choco install innosetup

    - name: Install Qt (All)
      shell: bash
      run: |
        ./scripts/install-qt.sh

    - name: Set Qt PATH for Test Discovery
      shell: bash
      if: env.BUILD_TEST == 'ON'
      run: |
        source ./scripts/env.sh
        echo "PATH=${QT_BIN}:${PATH}" >> ${GITHUB_ENV}
        echo "QT_QPA_PLATFORM=offscreen" >> ${GITHUB_ENV}

    - name: Configure and Build (All)
      shell: bash
      run: |
        ./scripts/build.sh \
          --build-type ${{ env.BUILD_TYPE }} \
          --test ${{ env.BUILD_TEST }} \
          --update-translations ${{ env.UPDATE_TRANSLATIONS }}

    - name: Unit Tests (All)
      shell: bash
      if: env.BUILD_TEST == 'ON'
      run: |
        source ./scripts/env.sh
        
        if [ "${PLATFORM}" == "windows" ]; then
          export WINDEPLOYQT=$(cygpath -w "${QT_BIN}/windeployqt.exe")
          export EXE_PATH=$(cygpath -w "${BUILD_DIR}/${{ env.BUILD_TYPE }}/${UT_NAME}.exe")
          ${WINDEPLOYQT} "${EXE_PATH}"
        "${EXE_PATH}" --gtest_output=stderr
        else
          "${BUILD_DIR}/tests/${UT_NAME}" --gtest_output=stderr
        fi


    - name: Smoke Test (All)
      shell: bash
      run: |
        ./scripts/run.sh --build-type ${{ env.BUILD_TYPE }} --smoke-test

    - name: Static Analysis (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        source ./scripts/env.sh
        clang-tidy -p "${BUILD_DIR}" $(find "${PROJECT_ROOT}/src" -type f -regextype posix-extended -regex ".*\.(cpp|h)")

    - name: Bundle Application Native (Linux)
      if: runner.os == 'Linux'
      run: |
        ./.github/scripts/linux-bundle-native.sh

    - name: Bundle Application AppImage (Linux)
      if: runner.os == 'Linux'
      run: |
        ./.github/scripts/linux-bundle-appimage.sh

    - name: Bundle Application (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        source ./scripts/env.sh
        export APP_PATH="${BUILD_DIR}/${APP_NAME}.app"
        "${QT_BIN}/macdeployqt" "${APP_PATH}"

    - name: Bundle Application (Windows)
      if: runner.os == 'Windows'
      shell: bash
      run: |
        source ./scripts/env.sh
        export WINDEPLOYQT=$(cygpath -w "${QT_BIN}/windeployqt.exe")
        export EXE_PATH=$(cygpath -w "${BUILD_DIR}/${{ env.BUILD_TYPE }}/${APP_NAME}.exe")

        ${WINDEPLOYQT} "${EXE_PATH}"
        
        export ISS_PATH=$(cygpath -w "${{ github.workspace }}/inno.iss")
        cat > "${ISS_PATH}" <<EOF
        [Setup]
        AppName=${APP_NAME}
        AppVersion=${APP_VERSION}
        DefaultDirName={commonpf}\\${APP_NAME}
        OutputDir=${BUILD_DIR}
        OutputBaseFilename=${APP_NAME}Installer
        Compression=lzma
        SolidCompression=yes
        SetupIconFile=${APP_ICON}

        [Files]
        Source: "${BUILD_DIR}\\${{ env.BUILD_TYPE }}\\${APP_NAME}.exe"; DestDir: "{app}"; Flags: ignoreversion
        Source: "${BUILD_DIR}\\${{ env.BUILD_TYPE }}\\*.dll"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs
        Source: "${BUILD_DIR}\\${{ env.BUILD_TYPE }}\\platforms\\*"; DestDir: "{app}\\platforms"; Flags: ignoreversion recursesubdirs

        [Icons]
        Name: "{group}\\${APP_NAME}"; Filename: "{app}\\${APP_NAME}.exe"
        Name: "{commondesktop}\\${APP_NAME}"; Filename: "{app}\\${APP_NAME}.exe"
        EOF

        cat "${ISS_PATH}"
        iscc "${ISS_PATH}"

    - name: Move Artifact to Uploads
      shell: bash
      run: |
        source ./scripts/env.sh
        mkdir -p "${{ env.UPLOAD_DIR }}"
        
        if [ -e "${PROJECT_ROOT}/${APP_NAME}-${APP_VERSION}.AppImage" ]; then
          mv -v "${PROJECT_ROOT}/${APP_NAME}-${APP_VERSION}.AppImage" "${{ env.UPLOAD_DIR }}"
        fi
        
        if [ -e "${PROJECT_ROOT}/${APP_NAME}-${APP_VERSION}.tar.gz" ]; then
          mv -v "${PROJECT_ROOT}/${APP_NAME}-${APP_VERSION}.tar.gz" "${{ env.UPLOAD_DIR }}"
        fi

        if [ -e "${BUILD_DIR}/${APP_NAME}.app" ]; then
          mv -v "${BUILD_DIR}/${APP_NAME}.app" "${{ env.UPLOAD_DIR }}"
        fi

        if [ -e "${BUILD_DIR}/${APP_NAME}Installer.exe" ]; then
          mv -v "${BUILD_DIR}/${APP_NAME}Installer.exe" "${{ env.UPLOAD_DIR }}"
        fi

    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}
        path: ${{ env.UPLOAD_DIR }}